#!/usr/bin/env bash
# Generates mssql/sql_exporter.yml (git-ignored — it holds passwords).
#
# Two sources, in order of preference:
#   1. mssql/servers.conf  — one "<name> <DSN>" per line. Use this for ONE OR MANY servers.
#   2. MSSQL_DSN in .env   — single-server fallback so older setups keep working.
#
# Called automatically by scripts/deploy.sh. Safe to run on its own.
set -euo pipefail
cd "$(dirname "$0")/.."

# SQL Server is only monitored when COMPOSE_PROFILES includes "mssql".
case ",${COMPOSE_PROFILES:-}," in
  *,mssql,*) ;;
  *)
    printf '%s
' "# GENERATED — SQL Server monitoring is OFF (COMPOSE_PROFILES has no 'mssql')."       > prometheus/targets/mssql.yml
    echo "SQL Server monitoring disabled (COMPOSE_PROFILES has no 'mssql') — no targets scraped."
    exit 0 ;;
esac

CONF="mssql/servers.conf"
OUT="mssql/sql_exporter.yml"
TMP="${OUT}.tmp"

# Never leave a half-written .tmp behind on a bad config line.
trap 'rm -f "$TMP"' EXIT

# name<TAB>dsn pairs collected here
targets=()

if [ -f "$CONF" ]; then
  lineno=0
  while IFS= read -r line || [ -n "$line" ]; do
    lineno=$((lineno + 1))
    line="${line%%$'\r'}"                       # tolerate CRLF
    line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    case "$line" in ''|\#*) continue ;; esac    # skip blanks/comments
    name="${line%%[[:space:]]*}"                # first field
    dsn="${line#*[[:space:]]}"                  # rest of the line
    dsn="$(printf '%s' "$dsn" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    if [ -z "$name" ] || [ -z "$dsn" ] || [ "$name" = "$dsn" ]; then
      echo "ERROR: $CONF line ${lineno} is not '<name> <DSN>':" >&2; echo "       ${line}" >&2; exit 1
    fi
    case "$dsn" in *"'"*) echo "ERROR: DSN for '$name' contains a single quote." >&2; exit 1 ;; esac
    targets+=("$name"$'\t'"$dsn")
  done < "$CONF"
  [ "${#targets[@]}" -gt 0 ] || { echo "ERROR: $CONF has no servers." >&2; exit 1; }
  src="$CONF"
elif [ -n "${MSSQL_DSN:-}" ]; then
  # Derive a readable name from the DSN's host:port (everything after @, before ?)
  name="$(printf '%s' "$MSSQL_DSN" | sed -e 's#.*@##' -e 's#[?/].*##')"
  [ -n "$name" ] || name="sqlserver"
  targets+=("$name"$'\t'"$MSSQL_DSN")
  src=".env (MSSQL_DSN)"
else
  echo "ERROR: no SQL Server configured." >&2
  echo "  Either: cp mssql/servers.conf.example mssql/servers.conf   (one or many servers)" >&2
  echo "  Or:     set MSSQL_DSN in .env                              (single server)" >&2
  exit 1
fi

{
  echo "# GENERATED by scripts/render-mssql-config.sh from ${src} — do not edit by hand."
  echo "global:"
  echo "  scrape_timeout: 10s"
  echo "  min_interval: 0s"
  echo
  echo "jobs:"
  echo "  - job_name: mssql"
  echo "    collectors: [mssql_standard]"
  echo "    static_configs:"
  echo "      - targets:"
  for t in "${targets[@]}"; do
    n="${t%%$'\t'*}"; d="${t#*$'\t'}"
    printf "          '%s': '%s'\n" "$n" "$d"
  done
  echo
  echo "collector_files:"
  echo '  - "mssql_standard.collector.yml"'
} > "$TMP"
mv "$TMP" "$OUT"

echo "Rendered $OUT from ${src} (${#targets[@]} SQL Server(s)):"
for t in "${targets[@]}"; do echo "  - ${t%%$'\t'*}"; done
