#!/usr/bin/env bash
# Generates, from mongodb/servers.conf:
#   docker-compose.override.yml  one small exporter container per MongoDB server
#                                (Compose loads this file automatically)
#   prometheus/targets/mongodb.yml   the matching scrape targets (with env labels)
#
# Falls back to a single server from MONGODB_URI in .env when servers.conf is absent.
# With neither, both files are still written (empty/placeholder) so nothing breaks.
#
# Called automatically by scripts/deploy.sh. Safe to run on its own.
set -euo pipefail
cd "$(dirname "$0")/.."

CONF="mongodb/servers.conf"
COMPOSE="docker-compose.override.yml"
TARGETS="prometheus/targets/mongodb.yml"
BASE_PORT=9216

trap 'rm -f "${COMPOSE}.tmp" "${TARGETS}.tmp"' EXIT
trim() { printf "%s" "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

names=(); uris=(); envs=()

if [ -f "$CONF" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%$'\r'}"
    case "$line" in ''|\#*) continue ;; esac
    IFS='|' read -ra parts <<< "$line"
    name="$(trim "${parts[0]:-}")"; uri="$(trim "${parts[1]:-}")"; envv=""
    for ((i=2; i<${#parts[@]}; i++)); do
      f="$(trim "${parts[i]}")"
      case "$f" in env=*) envv="$(trim "${f#env=}")" ;; esac
    done
    [ -n "$name" ] && [ -n "$uri" ] || { echo "ERROR: $CONF line needs '<name> | <URI>': $line" >&2; exit 1; }
    case "$name" in *[!A-Za-z0-9_-]*) echo "ERROR: name '$name' — letters, digits, - or _ only." >&2; exit 1 ;; esac
    case "$uri" in mongodb://*|mongodb+srv://*) ;; *) echo "ERROR: URI for '$name' must start with mongodb:// or mongodb+srv://" >&2; exit 1 ;; esac
    names+=("$name"); uris+=("$uri"); envs+=("$envv")
  done < "$CONF"
elif [ -n "${MONGODB_URI:-}" ]; then
  n="$(printf '%s' "$MONGODB_URI" | sed -e 's#.*@##' -e 's#[/?].*##' -e 's#:#-#g')"
  names+=("${n:-mongodb}"); uris+=("$MONGODB_URI"); envs+=("")
fi

{
  echo "# GENERATED by scripts/render-mongodb-config.sh — do not edit by hand."
  echo "# Edit mongodb/servers.conf, then run: bash scripts/deploy.sh"
  echo "services:"
  if [ "${#names[@]}" -eq 0 ]; then
    # No MongoDB configured. A never-activated placeholder keeps the file valid.
    echo "  mongodb-exporter-placeholder:"
    echo "    image: prom/blackbox-exporter:\${BLACKBOX_EXPORTER_VERSION}"
    echo "    profiles: [\"__none__\"]"
  else
    port=$BASE_PORT
    for i in "${!names[@]}"; do
      echo "  mongodb-exporter-${names[$i]}:"
      echo "    image: percona/mongodb_exporter:\${MONGODB_EXPORTER_VERSION}"
      echo "    restart: unless-stopped"
      echo "    profiles: [mongodb]"
      echo "    command:"
      echo "      - --mongodb.uri=${uris[$i]}"
      echo "      - --collect-all"
      echo "    ports:"
      echo "      - \"${port}:9216\""
      port=$((port + 1))
    done
  fi
} > "${COMPOSE}.tmp"

{
  echo "# GENERATED by scripts/render-mongodb-config.sh — do not edit by hand."
  echo "# Edit mongodb/servers.conf, then run: bash scripts/deploy.sh"
  for i in "${!names[@]}"; do
    echo "- targets: ['mongodb-exporter-${names[$i]}:9216']"
    echo "  labels:"
    echo "    job: mongodb"
    echo "    instance: '${names[$i]}'"
    [ -n "${envs[$i]}" ] && echo "    env: '${envs[$i]}'"
  done
} > "${TARGETS}.tmp"

mv "${COMPOSE}.tmp" "$COMPOSE"
mv "${TARGETS}.tmp" "$TARGETS"

if [ "${#names[@]}" -eq 0 ]; then
  echo "Rendered $COMPOSE (no MongoDB servers configured)"
else
  echo "Rendered $COMPOSE and $TARGETS (${#names[@]} MongoDB server(s)):"
  for i in "${!names[@]}"; do echo "  - ${names[$i]}${envs[$i]:+  [env=${envs[$i]}]}"; done
  echo "  Remember: COMPOSE_PROFILES must include 'mongodb' in .env"
fi
