#!/usr/bin/env bash
# Generates, from blackbox/apis.conf:
#   blackbox/blackbox.yml          = blackbox.base.yml + one module per API (holds API keys — git-ignored)
#   prometheus/targets/api.yml     = one probe target per API
#
# Line format (fields separated by |):
#   <name> | <url> [| <Header>: <value>] [| <option>=<value>] ...
#
# Headers  : any field containing ':' that is not a known option, e.g.  X-API-Key: abc123
#            (repeatable — list several header fields)
# Options  : method=POST            HTTP verb (default GET)
#            body={"a":1}           request body (implies Content-Type: application/json
#                                   unless you set content-type= yourself)
#            content-type=text/xml  overrides the body's content type
#            expect=200,201         status codes counted as healthy (default: any 2xx)
#            match=<regexp>         response body must match this, else the probe fails
#            insecure=true          skip TLS certificate verification (self-signed certs)
#            timeout=20s            per-probe timeout (default 10s)
#
# If apis.conf does not exist, blackbox.yml is just a copy of the base and no API
# targets are produced (nothing breaks — you simply aren't monitoring any APIs).
#
# Called automatically by scripts/deploy.sh. Safe to run on its own.
set -euo pipefail
cd "$(dirname "$0")/.."

CONF="blackbox/apis.conf"
BASE="blackbox/blackbox.base.yml"
OUT="blackbox/blackbox.yml"
TARGETS="prometheus/targets/api.yml"

[ -f "$BASE" ] || { echo "ERROR: $BASE missing." >&2; exit 1; }

# Never leave half-written .tmp files behind if we exit on a bad config line.
trap 'rm -f "${OUT}.tmp" "${TARGETS}.tmp"' EXIT

# YAML single-quoted scalars escape a quote by doubling it.
yq_escape() { printf "%s" "$1" | sed "s/'/''/g"; }
trim()      { printf "%s" "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

cp "$BASE" "${OUT}.tmp"
{
  echo "# GENERATED by scripts/render-api-config.sh — do not edit by hand."
  echo "# Edit blackbox/apis.conf, then run: bash scripts/deploy.sh"
} > "${TARGETS}.tmp"

count=0
if [ -f "$CONF" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%$'\r'}"
    case "$line" in ''|\#*) continue ;; esac

    IFS='|' read -ra parts <<< "$line"
    name="$(trim "${parts[0]:-}")"
    url="$(trim "${parts[1]:-}")"

    [ -n "$name" ] && [ -n "$url" ] || { echo "ERROR: $CONF line needs '<name> | <url>': $line" >&2; exit 1; }
    case "$name" in *[!A-Za-z0-9_-]*) echo "ERROR: API name '$name' — use letters, digits, - or _ only." >&2; exit 1 ;; esac
    case "$url" in http://*|https://*) ;; *) echo "ERROR: URL for '$name' must start with http:// or https://" >&2; exit 1 ;; esac

    method="GET"; body=""; ctype=""; expect=""; match=""; insecure=""; timeout="10s"
    headers=()

    for ((i = 2; i < ${#parts[@]}; i++)); do
      f="$(trim "${parts[i]}")"
      [ -n "$f" ] || continue
      key="$(printf '%s' "$f" | cut -d= -f1 | tr '[:upper:]' '[:lower:]')"
      val="$(trim "${f#*=}")"
      case "$key" in
        method)                  method="$(printf '%s' "$val" | tr '[:lower:]' '[:upper:]')" ;;
        body)                    body="$val" ;;
        content-type|content_type) ctype="$val" ;;
        expect|expect_status)    expect="$val" ;;
        match)                   match="$val" ;;
        insecure)                insecure="$val" ;;
        timeout)                 timeout="$val" ;;
        *)
          case "$f" in
            *:*) headers+=("$f") ;;
            *) echo "ERROR: '$name': cannot parse field '$f' (need 'Header: value' or 'option=value')." >&2; exit 1 ;;
          esac ;;
      esac
    done

    # A body with no explicit content type defaults to JSON.
    if [ -n "$body" ] && [ -z "$ctype" ]; then ctype="application/json"; fi

    {
      echo
      echo "  api_${name}:"
      echo "    prober: http"
      echo "    timeout: ${timeout}"
      echo "    http:"
      echo "      method: ${method}"
      if [ -n "$expect" ]; then
        echo "      valid_status_codes: [$(printf '%s' "$expect" | tr -d ' ')]"
      else
        echo "      valid_status_codes: []   # 2xx = healthy"
      fi
      echo "      follow_redirects: true"
      echo "      preferred_ip_protocol: ip4"
      if [ -n "${headers[*]:-}" ] || [ -n "$ctype" ]; then
        echo "      headers:"
        [ -n "$ctype" ] && echo "        Content-Type: '$(yq_escape "$ctype")'"
        for h in "${headers[@]:-}"; do
          [ -n "$h" ] || continue
          hname="$(trim "${h%%:*}")"
          hval="$(trim "${h#*:}")"
          [ -n "$hname" ] && [ -n "$hval" ] || { echo "ERROR: header for '$name' must be 'Name: value'." >&2; exit 1; }
          echo "        ${hname}: '$(yq_escape "$hval")'"
        done
      fi
      [ -n "$body" ] && echo "      body: '$(yq_escape "$body")'"
      if [ -n "$match" ]; then
        echo "      fail_if_body_not_matches_regexp:"
        echo "        - '$(yq_escape "$match")'"
      fi
      case "$insecure" in
        true|yes|1) echo "      tls_config:"; echo "        insecure_skip_verify: true" ;;
      esac
    } >> "${OUT}.tmp"

    {
      echo "- targets: ['$(yq_escape "$url")']"
      echo "  labels:"
      echo "    job: api"
      echo "    api: '${name}'"
      echo "    module: 'api_${name}'"
    } >> "${TARGETS}.tmp"

    count=$((count + 1))
  done < "$CONF"
fi

mv "${OUT}.tmp" "$OUT"
mv "${TARGETS}.tmp" "$TARGETS"

if [ "$count" -eq 0 ]; then
  echo "Rendered $OUT (no APIs configured — create blackbox/apis.conf to add some)"
else
  echo "Rendered $OUT and $TARGETS (${count} API endpoint(s)):"
  grep -oE "^  api_[A-Za-z0-9_-]+:" "$OUT" | sed 's/^  api_/  - /; s/:$//'
fi
