#!/usr/bin/env bash
# Generates, from blackbox/apis.conf:
#   blackbox/blackbox.yml          = blackbox.base.yml + one module per API (holds API keys — git-ignored)
#   prometheus/targets/api.yml     = one probe target per API
#
# If apis.conf does not exist, blackbox.yml is just a copy of the base and no API
# targets are produced (nothing breaks — you simply aren't monitoring any APIs).
#
# Called automatically by scripts/deploy.sh. Safe to run on its own.
set -euo pipefail
cd "$(dirname "$0")/.."

CONF="blackbox/apis.conf"
BASE="blackbox/blackbox.base.yml"
OUT="blackbox/blackbox.yml"
TARGETS="prometheus/targets/api.yml"

[ -f "$BASE" ] || { echo "ERROR: $BASE missing." >&2; exit 1; }

cp "$BASE" "${OUT}.tmp"

{
  echo "# GENERATED by scripts/render-api-config.sh — do not edit by hand."
  echo "# Edit blackbox/apis.conf, then run: bash scripts/deploy.sh"
} > "${TARGETS}.tmp"

count=0
if [ -f "$CONF" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%$'\r'}"
    case "$line" in ''|\#*) continue ;; esac

    name="$(printf '%s' "$line" | cut -d'|' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    url="$(printf '%s'  "$line" | cut -d'|' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    hdr="$(printf '%s'  "$line" | cut -d'|' -f3- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

    [ -n "$name" ] && [ -n "$url" ] || { echo "ERROR: $CONF line needs '<name> | <url>': $line" >&2; exit 1; }
    case "$name" in *[!A-Za-z0-9_-]*) echo "ERROR: API name '$name' — use letters, digits, - or _ only." >&2; exit 1 ;; esac
    case "$url" in http://*|https://*) ;; *) echo "ERROR: URL for '$name' must start with http:// or https://" >&2; exit 1 ;; esac

    # blackbox module for this API (carries its auth header, if any)
    {
      echo
      echo "  api_${name}:"
      echo "    prober: http"
      echo "    timeout: 10s"
      echo "    http:"
      echo "      method: GET"
      echo "      valid_status_codes: []   # 2xx = healthy"
      echo "      follow_redirects: true"
      echo "      preferred_ip_protocol: ip4"
      if [ -n "$hdr" ]; then
        hname="${hdr%%:*}"
        hval="$(printf '%s' "${hdr#*:}" | sed -e 's/^[[:space:]]*//')"
        [ -n "$hname" ] && [ -n "$hval" ] || { echo "ERROR: header for '$name' must be 'Name: value'." >&2; exit 1; }
        case "$hval" in *"'"*) echo "ERROR: header value for '$name' contains a single quote." >&2; exit 1 ;; esac
        echo "      headers:"
        echo "        ${hname}: '${hval}'"
      fi
    } >> "${OUT}.tmp"

    # prometheus probe target for this API
    {
      echo "- targets: ['${url}']"
      echo "  labels:"
      echo "    job: api"
      echo "    api: '${name}'"
      echo "    module: 'api_${name}'"
    } >> "${TARGETS}.tmp"

    count=$((count + 1))
  done < "$CONF"
fi

mv "${OUT}.tmp" "$OUT"
mv "${TARGETS}.tmp" "$TARGETS"

if [ "$count" -eq 0 ]; then
  echo "Rendered $OUT (no APIs configured — create blackbox/apis.conf to add some)"
else
  echo "Rendered $OUT and $TARGETS (${count} API endpoint(s)):"
  grep -oE "^  api_[A-Za-z0-9_-]+:" "$OUT" | sed 's/^  api_/  - /; s/:$//'
fi
